// <auto-generated />
namespace Ticketmanagment.DataAccess.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCommonLookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCommonLookup));
        
        string IMigrationMetadata.Id
        {
            get { return "202407081053345_addCommonLookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
